version: '3'
services:
  mongo:
    image: mongo:4
    volumes:
      - ./db:/data/db
  genieacs-cwmp: &defaults
    build: .
    image: quay.io/swoga/genieacs
    init: true
    env_file: config.env
    command: /usr/local/bin/genieacs-cwmp
    ports:
      - 7547:7547
  genieacs-nbi:
    <<: *defaults
    command: /usr/local/bin/genieacs-nbi
    ports:
      - 7557:7557
  genieacs-fs:
    <<: *defaults
    command: /usr/local/bin/genieacs-fs
    ports:
      - 7567:7567
  genieacs-ui:
    <<: *defaults
    command: /usr/local/bin/genieacs-ui
    ports:
      - 3000:3000
  mongo-express: 
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo
